name: 'Commit Comment'
description: 'Create a comment for a commit on GitHub'
inputs:
  token:
    description: 'The GitHub authentication token'
    default: ${{ github.token }}
  repository:
    description: 'The full name of the target repository.'
    default: ${{ github.repository }}
  sha:
    description: 'The commit SHA.'
  path:
    description: 'Relative path of the file to comment on.'
  position:
    description: 'Line index in the diff to comment on.'
  comment-id:
    description: 'The id of the comment to update.'
  body:
    description: 'The comment body. Cannot be used in conjunction with `body-path`.'
  body-path:
    description: 'The path to a file containing the comment body. Cannot be used in conjunction with `body`.'
  edit-mode:
    description: 'The mode when updating a comment, "replace" or "append".'
    default: 'append'
  append-separator:
    description: 'The separator to use when appending to an existing comment. (`newline`, `space`, `none`)'
    default: 'newline'
  reactions:
    description: 'A comma or newline separated list of reactions to add to the comment.'
  reactions-edit-mode:
    description: 'The mode when updating comment reactions, "replace" or "append".'
    default: 'append'
outputs:
  comment-id:
    description: 'The id of the created commit comment'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'message-square'  
  color: 'gray-dark'
