name: 'Commit Comment'
description: 'Create a comment for a commit on GitHub'
inputs:
  token:
    description: 'The GitHub authentication token'
    default: ${{ github.token }}
  repository:
    description: 'The full name of the target repository.'
    default: ${{ github.repository }}
  sha:
    description: 'The commit SHA.'
  body:
    description: 'The contents of the comment.'
    required: true
  path:
    description: 'Relative path of the file to comment on.'
  position:
    description: 'Line index in the diff to comment on.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'message-square'  
  color: 'gray-dark'
